services:
    rabbitmq:
        image: rabbitmq:4-management
        ports:
            - 15672:15672
    challenge:
        build:
            context: ./Builds/Php
            target: php
        volumes:
            - ./Apps/Worker:/var/www