services:
    rabbitmq:
        image: rabbitmq:4-management
        ports:
            - 15672:15672
    #add sh to check that rabbitmq is started
    capital:
        build:
            context: ./Apps/CapitalWorker
        volumes:
            - ./Apps/CapitalWorker:/var/www
        restart: on-failure
        depends_on:
            rabbitmq:
                condition: service_started
    country:
        build:
            context: ./Apps/CountryWorker
        volumes:
            - ./Apps/CountryWorker:/var/www
        restart: on-failure
        depends_on:
            rabbitmq:
                  condition: service_started