name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    defaults:
      run:
        working-directory: ./Apps/Worker
    runs-on: ubuntu-latest
    steps:
      # Mandatory : fetch the current repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # To be faster, use cache system for the Composer
        - name: Cache Composer dependencies
          uses: actions/cache@v3
          with:
            path: /tmp/composer-cache
            key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

        - name: Installing dependencies
          uses: php-actions/composer@v6
          with:
            container_workdir: /
            php_version: 8.3
            php_extensions: "json zip sodium bcmath"

        # Install composer dependencies, and dump env
        - name: Composer install
          run: |
            composer install --no-dev --no-progress --no-scripts --prefer-dist -a
        - name: unit test
          uses: php-actions/phpunit@v3
          with:
            version: 9.6
            php_version: 8.1
            php_extensions: "json zip sodium bcmath"
            args: "-d date.timezone=Europe/Paris"
            memory_limit: 300M
            configuration: phpunit.xml.dist
            testsuite: unittest