name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    defaults:
      run:
        working-directory: ./Apps/Worker
    runs-on: ubuntu-latest
    steps:
      # Mandatory : fetch the current repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # To be faster, use cache system for the Composer
        - name: Get Composer Cache Directory
          id: composer-cache
          run: |
            echo "::set-output name=dir::$(composer config cache-files-dir)"
        - name: Cache composer (vendor)
          uses: actions/cache@v3
          with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-
        # Define the right PHP environment
        # https://github.com/shivammathur/setup-php (community)
        - name: Environment for PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'
            extensions: json, zip, sodium, bcmath
            tools: composer:v2
            coverage: none
          env:
            update: true

        # Ensure that composer.json is valid
        - name: Validate composer.json and composer.lock
          run: composer validate

        # Install composer dependencies, and dump env
        - name: Composer install
          run: |
            composer install --no-dev --no-progress --no-scripts --prefer-dist -a
        - name: unit test
        - name: Composer install
          run: |
            composer install --no-dev --no-progress --no-scripts --prefer-dist -a
        - name: unit test
          uses: php-actions/phpunit@v3
          with:
            version: 9.6
            php_version: 8.1
            php_extensions: "json zip sodium bcmath"
            args: "-d date.timezone=Europe/Paris"
            memory_limit: 300M
            configuration: phpunit.xml.dist
            testsuite: unittest